export const AUDIT_EXPORT_MODULES = [
  { key: 'job_order', label: 'Job Orders' },
  { key: 'dispatch', label: 'Fleet Dispatch' },
  { key: 'tracking', label: 'Tracking' },
  { key: 'ocr', label: 'OCR Review' },
  { key: 'notification', label: 'Notifications' },
  { key: 'driver', label: 'Drivers' },
  { key: 'vehicle', label: 'Vehicles' },
  { key: 'reports', label: 'Reports' },
  { key: 'settings', label: 'System Settings' },
  { key: 'auth', label: 'Authentication' },
  { key: 'user', label: 'Master Data' },
  { key: 'audit', label: 'Audit Logs' },
]

export const AUDIT_ACTION_CATEGORIES = [
  { key: 'created', label: 'Created' },
  { key: 'updated', label: 'Updated' },
  { key: 'deleted', label: 'Deleted' },
  { key: 'assigned', label: 'Assigned' },
  { key: 'completed', label: 'Completed' },
  { key: 'login', label: 'Login' },
  { key: 'logout', label: 'Logout' },
  { key: 'exported', label: 'Exported' },
  { key: 'imported', label: 'Imported' },
  { key: 'failed_login', label: 'Failed Login' },
  { key: 'password_reset', label: 'Password Reset' },
]

export const AUDIT_EXPORT_ROLES = [
  { value: 'all', label: 'All Roles' },
  { value: 'admin', label: 'Admin' },
  { value: 'dispatcher', label: 'Dispatcher' },
  { value: 'manager', label: 'Manager' },
  { value: 'driver', label: 'Driver' },
  { value: 'customer', label: 'Client' },
]

export const AUDIT_INCLUDE_OPTIONS = [
  { key: 'include_logo', label: 'Include logo', default: true },
  { key: 'include_page_numbers', label: 'Include page numbers', default: true },
  { key: 'include_generated_by', label: 'Include generated by', default: true },
  { key: 'include_timestamp', label: 'Include export timestamp', default: true },
  { key: 'include_filters_summary', label: 'Include filters summary', default: true },
  { key: 'include_company', label: 'Include company information', default: true },
  { key: 'include_signature', label: 'Include digital signature area', default: false },
  { key: 'include_watermark', label: 'Include watermark', default: false },
]

export const EXPORT_PROGRESS_STEPS = [
  'Preparing report…',
  'Loading animation',
  'Compressing PDF…',
  'Generating pages…',
  'Finalizing…',
]
