<?php

namespace App\Services\Reports;

use Dompdf\Dompdf;
use Dompdf\Options;
use Illuminate\Support\Facades\View;

class PdfReportRenderer
{
    /**
     * @param  list<string>  $headers
     * @param  list<list<string|int|float|null>>  $rows
     */
    public function render(ReportMetadata $meta, array $headers, array $rows, string $filename): \Symfony\Component\HttpFoundation\Response
    {
        $orientation = $meta->orientation(count($headers));
        $html = View::make('reports.table', [
            'meta' => $meta,
            'headers' => $headers,
            'rows' => $rows,
            'companyName' => config('reports.company_name'),
            'productName' => config('reports.product_name'),
            'footerText' => config('reports.footer_text'),
            'exportedBy' => $meta->generatedByLabel(),
            'documentVersion' => config('reports.document_version', '1.0'),
            'jobOrderId' => $meta->summary['job_order_id'] ?? null,
            'logoDataUri' => $meta->exportOption('include_logo') ? $this->logoDataUri() : null,
            'orientation' => $orientation,
            'columnCount' => count($headers),
            'showPageNumbers' => $meta->exportOption('include_page_numbers'),
            'showGeneratedBy' => $meta->exportOption('include_generated_by'),
            'showTimestamp' => $meta->exportOption('include_timestamp'),
            'showFiltersSummary' => $meta->exportOption('include_filters_summary'),
            'showCompany' => $meta->exportOption('include_company'),
            'showSignature' => $meta->exportOption('include_signature'),
            'showWatermark' => $meta->exportOption('include_watermark'),
        ])->render();

        $options = new Options;
        $options->set('isRemoteEnabled', false);
        $options->set('defaultFont', 'DejaVu Sans');

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', $orientation);
        $dompdf->render();

        $canvas = $dompdf->getCanvas();
        $font = $dompdf->getFontMetrics()->getFont('DejaVu Sans', 'normal');
        if ($meta->exportOption('include_page_numbers')) {
            $canvas->page_text(
                $canvas->get_width() - 116,
                $canvas->get_height() - 28,
                'Page {PAGE_NUM} of {PAGE_COUNT}',
                $font,
                8,
                [0.28, 0.35, 0.45],
            );
        }
        if ($meta->exportOption('include_generated_by')) {
            $canvas->page_text(
                40,
                $canvas->get_height() - 28,
                'Generated by: '.$meta->generatedByLabel(),
                $font,
                7.5,
                [0.35, 0.42, 0.52],
            );
        }

        return response($dompdf->output(), 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="'.$filename.'"',
        ]);
    }

    private function logoDataUri(): ?string
    {
        $configured = config('reports.logo_path');
        $candidates = array_values(array_filter([
            is_string($configured) && $configured !== '' ? $configured : null,
            public_path('images/deliverex-logo.png'),
            public_path('favicon-192x192.png'),
            public_path('deliverexfavicon.png'),
            public_path('deliverexx.png'),
            dirname(base_path()).DIRECTORY_SEPARATOR.'frontend'.DIRECTORY_SEPARATOR.'public'.DIRECTORY_SEPARATOR.'favicon-192x192.png',
            dirname(base_path()).DIRECTORY_SEPARATOR.'frontend'.DIRECTORY_SEPARATOR.'public'.DIRECTORY_SEPARATOR.'deliverexfavicon.png',
            dirname(base_path()).DIRECTORY_SEPARATOR.'frontend'.DIRECTORY_SEPARATOR.'public'.DIRECTORY_SEPARATOR.'deliverexx.png',
        ]));

        foreach ($candidates as $path) {
            if (! is_file($path) || ! is_readable($path)) {
                continue;
            }

            $extension = strtolower(pathinfo($path, PATHINFO_EXTENSION));
            $mime = match ($extension) {
                'svg' => 'image/svg+xml',
                'jpg', 'jpeg' => 'image/jpeg',
                'webp' => 'image/webp',
                default => 'image/png',
            };

            return 'data:'.$mime.';base64,'.base64_encode((string) file_get_contents($path));
        }

        return null;
    }
}
