<?php

namespace App\Services\Reports;

use OpenSpout\Common\Entity\Cell;
use OpenSpout\Common\Entity\Row;
use OpenSpout\Common\Entity\Style\Style;
use OpenSpout\Writer\CSV\Writer as CsvWriter;
use OpenSpout\Writer\XLSX\Writer as XlsxWriter;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ReportSpreadsheetExporter
{
    /**
     * @param  list<string>  $headers
     * @param  iterable<list<string|int|float|null>>  $rows
     */
    public function toCsv(ReportMetadata $meta, array $headers, iterable $rows, string $filename): StreamedResponse
    {
        return response()->streamDownload(function () use ($meta, $headers, $rows) {
            $writer = new CsvWriter;
            $writer->openToFile('php://output');
            $this->writeMetadataRows($writer, $meta);
            $writer->addRow(Row::fromValues($headers));
            foreach ($rows as $row) {
                $writer->addRow(Row::fromValues($row));
            }
            $writer->close();
        }, $filename, [
            'Content-Type' => 'text/csv; charset=UTF-8',
        ]);
    }

    /**
     * @param  list<string>  $headers
     * @param  iterable<list<string|int|float|null>>  $rows
     */
    public function toXlsx(ReportMetadata $meta, array $headers, iterable $rows, string $filename): Response
    {
        $tmp = tempnam(sys_get_temp_dir(), 'dx_report_');
        $path = $tmp.'.xlsx';
        @unlink($tmp);

        $writer = new XlsxWriter;
        $writer->openToFile($path);

        $bold = (new Style)->setFontBold();
        foreach ($this->metadataRows($meta) as $line) {
            $writer->addRow(new Row([Cell::fromValue($line, $bold)]));
        }
        $writer->addRow(new Row([Cell::fromValue('')]));
        $writer->addRow(new Row(array_map(fn ($h) => Cell::fromValue($h, $bold), $headers)));

        foreach ($rows as $row) {
            $writer->addRow(Row::fromValues($row));
        }

        $writer->close();

        return response()->download($path, $filename, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        ])->deleteFileAfterSend(true);
    }

    /** @param  CsvWriter|XlsxWriter  $writer */
    private function writeMetadataRows($writer, ReportMetadata $meta): void
    {
        foreach ($this->metadataRows($meta) as $line) {
            $writer->addRow(Row::fromValues([$line]));
        }
        $writer->addRow(Row::fromValues(['']));
    }

    /** @return list<string> */
    private function metadataRows(ReportMetadata $meta): array
    {
        $company = config('reports.company_name');
        $product = config('reports.product_name');

        $lines = [
            $company,
            $product.' - '.$meta->reportTitle,
            'Generated by: '.$meta->generatedByLabel(),
            'Generated at: '.$meta->generatedAtLabel(),
            'Filters: '.implode(' | ', $meta->filterLines()),
        ];

        foreach ($meta->summary as $key => $value) {
            if ($value === null || $value === '') {
                continue;
            }
            $lines[] = ucwords(str_replace('_', ' ', (string) $key)).': '.$value;
        }

        return $lines;
    }
}
