<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $meta->reportTitle }}</title>
    <style>
        @page { margin: 36px 40px 52px 40px; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 10.5px; color: #1e293b; margin: 0; }
        .header { border-bottom: 2px solid #2563eb; padding-bottom: 14px; margin-bottom: 18px; }
        .brand-row { display: table; width: 100%; }
        .brand-left { display: table-cell; vertical-align: middle; width: 58%; }
        .brand-right { display: table-cell; vertical-align: middle; text-align: right; width: 42%; }
        .logo-box {
            width: 42px; height: 42px; border-radius: 8px; background: #2563eb; color: #fff;
            text-align: center; line-height: 42px; font-weight: bold; font-size: 16px;
            display: inline-block; margin-right: 10px; vertical-align: middle;
        }
        .company { font-size: 17px; font-weight: bold; color: #0f172a; margin: 0; display: inline-block; vertical-align: middle; }
        .product { font-size: 11px; color: #2563eb; font-weight: bold; margin: 4px 0 0; letter-spacing: 0.05em; text-transform: uppercase; }
        .report-title { font-size: 14px; font-weight: bold; margin: 0; color: #334155; }
        .meta { font-size: 9.5px; color: #64748b; line-height: 1.6; margin-top: 10px; }
        table.data { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.data th {
            background: #f1f5f9;
            color: #334155;
            font-size: 9px;
            text-transform: uppercase;
            letter-spacing: 0.04em;
            padding: 9px 8px;
            border: 1px solid #cbd5e1;
            text-align: left;
        }
        table.data td {
            padding: 8px;
            border: 1px solid #e2e8f0;
            font-size: 9px;
            vertical-align: top;
            word-wrap: break-word;
        }
        table.data tr:nth-child(even) td { background: #f8fafc; }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            font-size: 8.5px;
            color: #64748b;
            border-top: 1px solid #e2e8f0;
            padding: 8px 40px 0;
        }
        .footer-row { display: table; width: 100%; }
        .footer-left { display: table-cell; text-align: left; width: 50%; }
        .footer-right { display: table-cell; text-align: right; width: 50%; }
        .summary { margin: 12px 0 0; font-size: 9.5px; color: #475569; }
        .doc-meta { font-size: 9px; color: #94a3b8; margin-top: 4px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand-row">
            <div class="brand-left">
                <span class="logo-box">DX</span>
                <div style="display:inline-block; vertical-align:middle;">
                    <p class="company">{{ $companyName }}</p>
                    <p class="product">{{ $productName }}</p>
                </div>
            </div>
            <div class="brand-right">
                <p class="report-title">{{ $meta->reportTitle }}</p>
                <p class="doc-meta">Document version {{ $documentVersion ?? '1.0' }}@if(!empty($jobOrderId)) · Job Order #{{ $jobOrderId }}@endif</p>
            </div>
        </div>
        <div class="meta">
            Generated by: {{ $meta->generatedByLabel() }}<br>
            Exported by: {{ $exportedBy ?? $meta->generatedByLabel() }}<br>
            Generated at: {{ $meta->generatedAtLabel() }}<br>
            Filters: {{ implode(' · ', $meta->filterLines()) }}
        </div>
        @if (!empty($meta->summary))
            <div class="summary">
                @foreach ($meta->summary as $key => $value)
                    @if ($value !== null && $value !== '')
                        {{ ucwords(str_replace('_', ' ', $key)) }}: {{ $value }}@if (!$loop->last) · @endif
                    @endif
                @endforeach
            </div>
        @endif
    </div>

    <table class="data">
        <thead>
            <tr>
                @foreach ($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td>{{ $cell ?? '—' }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headers) }}">No records found for the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <div class="footer-row">
            <div class="footer-left">{{ $footerText }} · {{ $productName }} Enterprise Reporting</div>
            <div class="footer-right">Digital export · Confidential</div>
        </div>
    </div>
</body>
</html>
